version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy # Esta linha garante que o 'app' só inicie quando o 'mysql' estiver saudável
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: genesysjp
      MYSQL_DATABASE: crud-laravel
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck: # Adiciona uma verificação de saúde para o MySQL
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pgenesysjp"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s # Dá um tempo inicial para o MySQL subir antes de começar as verificações
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: genesysjp
      MYSQL_ROOT_PASSWORD: genesysjp
    depends_on:
      - mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
